### ISSUE TITLE
Crash when tracking before location is acquired

### ISSUE THREAD

**Issue by Maroniemann** [y20k/trackbook#3]
The app crashes when I press the "locate me" or "start tracking" buttons before my location has been acquired.

**Comment by y20k** [comment]
Hey @Maroniemann , thanks for reporting that issue!

There is another related issue, that I am working on. Trackbook currently does not check if the user has turned off "Location" in Android Settings. I am not saying that you had "Location" turned off. But in the course of fixing this Settings issue, your problem should vanish, too. My hope is that with the next update both problems should be resolved.

**Comment by y20k** [comment]
The new release ([0.9.2](https://github.com/y20k/trackbook/releases/tag/0.9.2)) probably / hopefully fixes your issue. If not, please drop a note.

**Comment by Maroniemann** [comment]
How long does it usually take for a new version to be available on F-Droid?

**Comment by y20k** [comment]
in my experience about 24 to 36 hours.

**Comment by Maroniemann** [comment]
I updated to 0.9.2 now and tested it a bit. When I start the app, regardless of my GPS settings, it always starts with a node at a persistent location node that is nowhere near me. It still crashes when trying to record with GPS turned off. Turning GPS on allows me to "locate me", which indicates that the persistent node is over an hour old. Also the source of the node is "network" even though my GPS is always set to "device only".

**Comment by y20k** [comment]
Hi.

Thanks for testing this. I will look into the issue next week. I do not have my Dev box at hand right now. There is a minor update out (0.9.3) that should fix a bug related to recording, but probably not related to your issue. 

I try to detect changes in System settings switches, to determine, if Location is on. Do you a see small toast warning that Trackbook needs Location services before the crash? If not there might be a bug in System settings state detection.

Best regards.

**Comment by y20k** [comment]
Hi there. Just a short note. I did experience the bug myself. That should help me finding the cause - as soon as I am back at my desk (= short vacation afk right now).

**Comment by y20k** [comment]
A strange thing happened. I was able to produce the crash while I was on vacation - with no PC to debug it.

Now - back at home - I cannot reproduce the crash anymore. So I need to guess what the problem is ... and I really have no clue. My only idea: somehow the method [`getLastKnownLocation`](https://github.com/y20k/trackbook/blob/deed2f624d93590c4929682839fae6c367684497/app/src/main/java/org/y20k/trackbook/helpers/LocationHelper.java#L55) does not work under some circumstances.

Version [0.9.4](https://github.com/y20k/trackbook/releases/tag/0.9.4) is out. It should not crash when `getLastKnownLocation` does not deliver a location. Instead you should see a short message: _"Location services not ready. Please retry."_

It is still possible that there is a bug somewhere deeper in [`LocationHelper.java`](https://github.com/y20k/trackbook/blob/master/app/src/main/java/org/y20k/trackbook/helpers/LocationHelper.java). But at the moment I do not know where.

**Comment by collectorgeneral** [comment]
@y20k 
Just experienced a similar situation with the beta apk you posted on #2 . It tracked fine, I had it running in the background. But as soon as I entered the app, it crashed. 

Perhaps write some sort of log to a text file? Maybe it will help you identify it.

**Comment by y20k** [comment]
Hi there,

any idea how to reproduce this bug? How did you re-enter the app? Did you use the notification to do so?

> Perhaps write some sort of log to a text file?

Android has an internal system log that logs everything. You can view it using [logcat](https://developer.android.com/studio/command-line/logcat.html). There are apps that let you view logcat on directly on your phone.

I use [aLogcat (free)](https://play.google.com/store/apps/details?id=org.jtb.alogcat&hl=en). It works great for me. But I had to give it the right to read my logs manually - one-time operation
1. `adb shell` (from PC -> if you run an terminal on device just step 2)
2. `pm grant org.jtb.alogcat android.permission.READ_LOGS`

There are probably newer alternatives that do not need any Terminal-Fu to work.

![2016-12-21-13 01 59](https://cloud.githubusercontent.com/assets/9103935/21390258/46cf0b08-c786-11e6-8d05-a92a9aef8b47.png)

**Comment by collectorgeneral** [comment]
@y20k 

I had it happen twice. Both times, I started tracking, went about doing my work. I got back home, and then tried to open the app to stop and save my current session. As soon as the app opened, it crashed. I am almost certain I tapped the notification to enter the app. 

Yes I am aware of logcat and the terminal thing, I was just too lazy to do it. Perhaps its about time I do though. So I will keep that in mind

**Comment by collectorgeneral** [comment]
@y20k 
Alright I got my lazy-ass to install [MatLog](https://github.com/plusCubed/matlog). Immediately I managed to capture 2 crashes, one when I was trying to stop recording, the other immediately after opening. Note that I tried to filter and save. If you find something is missing, let me know. I will upload full log. 
See attached log:
[2016-12-21-11-10-24-tb-crash.txt](https://github.com/y20k/trackbook/files/667027/2016-12-21-11-10-24-tb-crash.txt)

**Comment by y20k** [comment]
Thanks for sending me the crashog. It looks like the system wanted to kill the background service that runs if you activated tracking. That should not happen. Do you have a system optimizer running that tries to kill non-necessary apps and processes?

Anyway. I will have a look into it and see how I can (a) make the service stick around longer (b) handle killing by the system better.

AND: If you have any new crashlogs, please upload the relevant parts. Often crashlogs have a section "caused by" which sometimes directly points to the problematic code.

**Comment by collectorgeneral** [comment]
@y20k 
Sorry, I just realised I left out the most important section of catlog - the beginning of crash section >.>. I was working too quick with the logger and did not giving you the important bits. 

Here is the crash section:
[2016-12-21-11-10-24-tb-crash-CRASH-VERBOSE.txt](https://github.com/y20k/trackbook/files/669485/2016-12-21-11-10-24-tb-crash-CRASH-VERBOSE.txt)

Interesting to note that there is an exception that says it failed to parse the date.
`Caused by: java.text.ParseException: Failed to parse date ["Dec 20, 2016 21:06:11']: Invalid number: Dec  (at offset 0)`

Could it be that this and #5  are related?

**Comment by y20k** [comment]
This issue is resolved as far as I remember. Feel free to re-open.
